(() => {
  'use strict';
  const cards = window.KORNI_CARDS || [];
  const SETTINGS = Object.freeze({shuffleTasks:false});
  window.KORNI_SETTINGS = SETTINGS;
  const KEY = 'korni-omofony-trainer-v7';
  const PAGE_SIZE = 7;
  const shuffled = values => {const result=[...values];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
  const freshOrder = card => ({letters:shuffled(card.letterOptions),checks:shuffled(card.checkOptions)});
  const freshOrders = () => cards.map(freshOrder);
  const sameOptions = (saved,current) => Array.isArray(saved)&&saved.length===current.length&&[...saved].sort().every((value,index)=>value===[...current].sort()[index]);
  const freshProgress = () => cards.map(card => ({letter:null,checks:[],checkInput:'',letterLocked:false,checksLocked:false,letterCorrect:false,checksCorrect:false,letterMessage:'Выберите один вариант.',checkMessage:card.checkMode==='input'?'Введите проверочное слово.':'Отметьте подходящие слова.'}));
  let state = {current:0,progress:freshProgress(),journal:[],orders:freshOrders()};
  try { const saved=JSON.parse(localStorage.getItem(KEY)); if(saved?.progress?.length===cards.length) state=saved; } catch (_) {}
  if(!Array.isArray(state.orders)) state.orders=[];
  cards.forEach((card,index)=>{const order=state.orders[index];if(!order||!sameOptions(order.letters,card.letterOptions)||!sameOptions(order.checks,card.checkOptions))state.orders[index]=freshOrder(card)});
  state.orders.length=cards.length;
  state.progress.forEach(item=>{if(typeof item.checkInput!=='string')item.checkInput=''});
  const $ = id => document.getElementById(id);
  const el = {exercise:$('exercise'),frame:$('stickerFrame'),image:$('cardImage'),caption:$('imageCaption'),number:$('slideNumber'),badge:$('stateBadge'),letters:$('letterOptions'),checks:$('checkOptions'),checkPrompt:$('checkPrompt'),checkHint:$('checkHint'),lf:$('letterFeedback'),cf:$('checkFeedback'),prev:$('previousButton'),next:$('nextButton'),dots:$('pageDots'),bar:$('progressBar'),progress:$('progressText'),done:$('doneCount'),parts:$('partCount'),percent:$('scorePercent'),journal:$('journal'),errors:$('errorCount'),source:$('sourceNote'),jumpBack:$('jumpBack'),jumpForward:$('jumpForward')};
  const save = () => { try { localStorage.setItem(KEY,JSON.stringify(state)); } catch (_) {} };
  const same = (a,b) => a.length===b.length && [...a].sort().every((v,i)=>v===[...b].sort()[i]);
  const complete = p => p.letterCorrect && p.checksCorrect;
  function choice(text, selected, locked, action){const b=document.createElement('button');b.className='choice'+(selected?' selected':'');b.textContent=text;if(text.includes('\u0301')||/[Ёё]/.test(text)){const marked=text.replace(/([АЕЁИОУЫЭЮЯаеёиоуыэюя])\u0301/g,'<span class="stressed-vowel">$1́</span>').replace(/([Ёё])/g,'<span class="stressed-vowel">$1</span>');b.innerHTML=marked}b.disabled=locked;b.addEventListener('click',action);return b;}
  function feedback(node,message,ok,attempted){node.textContent=message;node.className='feedback '+(ok?'good':attempted?'bad':'muted');}
  function renderDots(){const start=Math.floor(state.current/PAGE_SIZE)*PAGE_SIZE,end=Math.min(start+PAGE_SIZE,cards.length);el.dots.innerHTML='';for(let i=start;i<end;i++){const b=document.createElement('button');b.className='dot'+(i===state.current?' active':'')+(complete(state.progress[i])?' done':'');b.textContent=i+1;b.title=cards[i].title;b.onclick=()=>{state.current=i;render()};el.dots.appendChild(b)}el.jumpBack.disabled=start===0;el.jumpForward.disabled=end===cards.length;}
  function renderJournal(){el.errors.textContent=state.journal.length;el.journal.innerHTML='';if(!state.journal.length){el.journal.innerHTML='<div class="empty">Здесь появятся ошибки и правильные ответы.<br>Пока всё чисто ✦</div>';return}state.journal.slice().reverse().forEach(x=>{const n=document.createElement('div');n.className='journal-entry';const s=document.createElement('strong');s.textContent=x.title;const d=document.createElement('span');d.textContent=`${x.kind}: выбрано «${x.chosen||'ничего'}» → правильно «${x.correct}»`;n.append(s,d);el.journal.appendChild(n)})}
  function score(){const done=state.progress.filter(complete).length,parts=state.progress.reduce((n,p)=>n+(p.letterCorrect?1:0)+(p.checksCorrect?1:0),0),percent=cards.length?Math.round(done/cards.length*100):0;el.done.textContent=done;el.parts.textContent=parts;el.percent.textContent=percent+'%';el.percent.parentElement.style.setProperty('--score',percent+'%');el.progress.textContent=`${done} из ${cards.length}`;el.bar.style.width=percent+'%';}
  function render(){if(!cards.length)return;state.current=Math.max(0,Math.min(state.current,cards.length-1));const c=cards[state.current],p=state.progress[state.current],order=state.orders[state.current];const verticalSlides=new Set([29,31,39,40,47,48,50,52,61,65]),isLargePortrait=verticalSlides.has(state.current+1);el.exercise.className=`exercise ${state.current>=68||isLargePortrait?'vertical':'horizontal'}${isLargePortrait?' portrait-large':''}`;el.frame.dataset.tone=String(state.current%5);el.caption.hidden=!c.overlayCaption;el.caption.textContent=c.overlayCaption||'';el.number.textContent=`${state.current+1} / ${cards.length}`;el.image.src=c.image;el.image.alt=c.title;el.badge.textContent=complete(p)?'Завершена':'Не завершена';el.badge.className='badge'+(complete(p)?' done':'');el.source.textContent=c.needsReview?`${c.source} · методическая пометка` : c.source;const special=c.checkMode==='dictionary'||c.checkMode==='stressed';el.checkPrompt.textContent=c.checkMode==='input'?'Введите проверочное слово':special?'Определите способ написания':'Найдите проверочное слово';el.checkHint.textContent=c.checkMode==='dictionary'?'У этого слова нет современной проверки ударением.':c.checkMode==='stressed'?'Выберите верное объяснение.':c.checkMode==='input'?'':'Выберите один вариант.';el.letters.innerHTML='';order.letters.forEach(v=>el.letters.appendChild(choice(v,p.letter===v,p.letterLocked,()=>{p.letter=v;save();render()})));el.checks.innerHTML='';if(c.checkMode==='input'){const input=document.createElement('input');input.className='check-input';input.type='text';input.value=p.checkInput;input.placeholder='Введите проверочное слово';input.disabled=p.checksLocked;input.setAttribute?.('aria-label','Проверочное слово');input.addEventListener('input',event=>{p.checkInput=event.target.value;save()});input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();check()}});el.checks.appendChild(input)}else{order.checks.forEach(v=>el.checks.appendChild(choice(v,p.checks.includes(v),p.checksLocked,()=>{const set=new Set(p.checks);set.has(v)?set.delete(v):set.add(v);p.checks=[...set];save();render()})))}feedback(el.lf,p.letterMessage,p.letterCorrect,p.letterMessage!=='Выберите один вариант.');feedback(el.cf,p.checkMessage,p.checksCorrect,p.checkMessage!=='Отметьте подходящие слова.');el.prev.disabled=state.current===0;el.next.disabled=state.current===cards.length-1;renderDots();renderJournal();score();save();}
  function journal(kind,chosen,correct){const c=cards[state.current];state.journal.push({id:Date.now()+Math.random(),cardId:c.id,title:c.title,kind,chosen,correct});if(state.journal.length>120)state.journal=state.journal.slice(-120)}
  const normalized = value => value.trim().toLocaleLowerCase('ru-RU').normalize('NFD').replace(/\u0301/g,'').replace(/ё/g,'е').replace(/\s+/g,' ');
  function check(){const c=cards[state.current],p=state.progress[state.current];if(!p.letterLocked){if(p.letter===c.correctLetter){p.letterCorrect=true;p.letterLocked=true;p.letterMessage=`Буква выбрана верно: ${c.correctLetter}.`}else{p.letterCorrect=false;p.letterMessage=p.letter?'В выборе буквы есть ошибка.':'Сначала выберите букву.';journal('буква',p.letter,c.correctLetter)}}if(!p.checksLocked){const inputMode=c.checkMode==='input';const inputCorrect=inputMode&&c.inputAnswers.some(answer=>normalized(answer)===normalized(p.checkInput));const selectedCorrect=!inputMode&&same(p.checks,c.correctChecks);if(inputCorrect||selectedCorrect){p.checksCorrect=true;p.checksLocked=true;p.checkMessage=c.checkMode==='dictionary'?'Верно: это словарное слово.':c.checkMode==='stressed'?'Верно: выбран правильный способ проверки.':`Верное проверочное слово: ${inputMode?p.checkInput:c.correctChecks.join(', ')}.`}else{p.checksCorrect=false;p.checkMessage=inputMode?(p.checkInput.trim()?'Это слово не входит в список нормативных ответов.':'Введите проверочное слово.'):(p.checks.length?'В выборе проверочных слов есть ошибка.':'Выберите проверочное слово.');journal(c.checkMode==='dictionary'||c.checkMode==='stressed'?'способ написания':'проверочное слово',inputMode?p.checkInput:p.checks.join(', '),c.correctChecks.join(', '))}}render()}
  $('checkButton').onclick=check;el.prev.onclick=()=>{if(state.current){state.current--;render()}};el.next.onclick=()=>{if(state.current<cards.length-1){state.current++;render()}};el.jumpBack.onclick=()=>{state.current=Math.max(0,(Math.floor(state.current/PAGE_SIZE)-1)*PAGE_SIZE);render()};el.jumpForward.onclick=()=>{state.current=Math.min(cards.length-1,(Math.floor(state.current/PAGE_SIZE)+1)*PAGE_SIZE);render()};
  $('resetSlide').onclick=()=>{const old=state.progress[state.current],next=freshProgress()[0];if(old.letterLocked)Object.assign(next,{letter:old.letter,letterLocked:true,letterCorrect:true,letterMessage:old.letterMessage});if(old.checksLocked)Object.assign(next,{checks:[...old.checks],checksLocked:true,checksCorrect:true,checkMessage:old.checkMessage});state.progress[state.current]=next;render()};
  $('resetAll').onclick=()=>{if(confirm('Сбросить весь прогресс и журнал ошибок?')){state={current:0,progress:freshProgress(),journal:[],orders:freshOrders()};render()}};
  document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&!el.prev.disabled)el.prev.click();if(e.key==='ArrowRight'&&!el.next.disabled)el.next.click();if((e.ctrlKey||e.metaKey)&&e.key==='Enter')check()});
  if (matchMedia('(pointer:fine)').matches && !matchMedia('(prefers-reduced-motion:reduce)').matches) {
    let lastTrail = 0;
    document.addEventListener('pointermove', e => {
      const now = performance.now(); if (now - lastTrail < 55) return; lastTrail = now;
      const glow = document.createElement('i'); glow.className = 'cursor-glow';
      glow.style.left = `${e.clientX}px`; glow.style.top = `${e.clientY}px`;
      document.body.appendChild(glow); setTimeout(() => glow.remove(), 650);
    });
  }
  render();
})();
